rvm:
  - 2.1
  - 2.2
  - 2.3.4
  - 2.4.1
  - ruby-head

gemfile:
  - Gemfile

before_install:
  - gem update bundler

script:
  - bundle exec rake test

matrix:
  allow_failures:
    - rvm: ruby-head
